name: dcurses
description: A library for console applications inspired by ncurses
version: 1.0.6
repository: https://github.com/Kibibibit/dcurses

environment:
  sdk: '>=2.16.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
